### ISSUE TITLE
All previous releases were deleted when v0.2.1 was released

### ISSUE THREAD

**Issue by apearce-nov** [dev-drprasad/delete-tag-and-release#20]
Not a bug, but all previous releases of this package were deleted when v0.2.1 was released, which will cause every workflow that uses this package to break. If there's no option to restore those releases, then this was a pretty frustrating oversight.

**Comment by thadguidry** [comment]
Hi @apearce-nov 
As a maintainer of workflows myself I completely understand the frustration.  The reasoning was to ensure Node16 was used across Runners.  Eventually workflows would have broken anyway.  The other reasoning was that prior to v0.2.0 there was possibility for accidental release deletions.

Having said that, I do understand that it's a minor inconvenience to update workflows if you have many repos.  Fortunately there are great ide extensions and tools to let you quickly search and replace via pattern and push updates to all the affected repos in one go rather than individually. Which might help you.

**Comment by Yimura** [comment]
You probably should have left the deprecation to Github themselves, removing older versions is a bad practice even if they're no longer going to work in the future because of changes to the platform.

By removing them early you've shifted the blame on the people using the package to yourself.

**Comment by constgen** [comment]
Sounds like a BIG surprize in the day of release, when everything suddenly stopped working.

**Comment by constgen** [comment]
What actually confuses me that documentation points to `v0.2`, but it actually doesn't exist

```yaml
- uses: dev-drprasad/delete-tag-and-release@v0.2
```

![image](https://user-images.githubusercontent.com/673144/226403336-28544479-85f3-44dc-8800-638612ab734b.png)

But `v0.2.1` did work

```yaml
- uses: dev-drprasad/delete-tag-and-release@v0.2.1
```

**Comment by thadguidry** [comment]
> What actually confuses me that documentation points to `v0.2`, but it actually doesn't exist

Fixed!  Example in README now shows `v0.2.1`

**Comment by plajjan** [comment]
Agree with @Yimura, better leave the deprecation to GitHub. I got bit by this now with failing builds forcing me to drop everything else and fix this. Had it been left to GH, I could deal with it in time, so in the future, please don't just remove old releases :)  Thanks for the action btw :)

**Comment by thadguidry** [comment]
@plajjan I didn't write the action.  I only maintain it with help from community.  Can you help us btw?  Maybe test `@master` version on something non-production in case of accidental release deletes that your ok with deleting.  Or setup a test repo and make some quick fake releases, etc. and try out `@master` version? We'd love the feedback and you can make a new issue.

**Comment by aaronmassicotte** [comment]
Please don't delete releases. It breaks our pipelines!

**Comment by thadguidry** [comment]
A new pre-release version has been released.  We expect no breaking changes in that pre-release, however since it is a pre-release, it should be tested first on non-production workflows or test repos with non-production releases.  Feedback in new issues would be most welcome!

Read release notes:  https://github.com/dev-drprasad/delete-tag-and-release/releases/tag/v1.0

Closing this issue now and looking forward to continued help from the community and feedback.

Special Thanks !!! to @wardellbagby for stepping up and helping add tests and improving the developer experience for other new contributors in the future!
