### ISSUE TITLE
Use GitHub Actions SDK

### ISSUE THREAD

**Issue by constgen** [dev-drprasad/delete-tag-and-release#22]
Not an issue, but a proposal. You can avoid a ton of unnecessary code if reuse GitHub Actions programmatic NodeJS API. The example of such JavaScript code can be found in this article https://levelup.gitconnected.com/how-to-move-a-git-tag-using-github-actions-e23a523eb325

You would be able to remove `fetch` utility and other boilerplate code

**Comment by thadguidry** [comment]
Yeap, thanks that's what I saw also.  I talked about this with @wardellbagby in PR #17. Specifically this resolved conversation: https://github.com/dev-drprasad/delete-tag-and-release/pull/17/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

@constgen Could you offer your help to begin that migration work in a draft PR?  I'd love to have your knowledge and would gladly welcome the help since I'm only helping maintain this now with total community help and don't have deep JS knowledge myself.
