### ISSUE TITLE
Ensure failing workflow steps do fail the workflow

### ISSUE THREAD

**Issue by thadguidry** [dev-drprasad/delete-tag-and-release#30]
I thought I saw an issue with Bundle checks or Tests where a workflow step might fail, but it will still pass because we might not be catching it correctly. I could be wrong however and would appreciate help.

**Comment by wardellbagby** [comment]
@thadguidry Can you link me to the Workflow run? I can take a look.

**Comment by wardellbagby** [comment]
I assume you're talking about the ones that ran for this PR, right? https://github.com/dev-drprasad/delete-tag-and-release/pull/31/checks

It looks like the Bundle Check did correctly fail _but_ that wouldn't have stopped you from being able to merge. In order to block merges until all checks pass, you'll have to [configure a branch protection rule for the master branch that requires certain checks to pass before allowing merges.](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule#creating-a-branch-protection-rule)

You'll likely want to enable all 3 of the current checks to be required before allowing merges.

If instead you're referring to the ["error messages" you see](https://github.com/dev-drprasad/delete-tag-and-release/actions/runs/4498220591/jobs/7914584055?pr=31#step:5:10) when running the tests, that's actually expected behavior. Since the tests run this Action's normal code as directly as possible, it logs as if it were really running. GitHub interprets those as error messages, since if it had outputted those messages when running as a real Action in a real repo, they would be error messages. But don't worry; the test isn't _really_ failing. 

However, if you'd prefer, I can configure Jest to hide that output entirely.

**Comment by thadguidry** [comment]
The output was fine and errors on test where they are expected is also fine, as long as tests are correct and are passing.
If `npm run package` itself has an exit error (i.e. there is no package found to run), then that workflow step will indeed fail and hence the workflow will fail?  Are you confident in all the workflow steps themselves (Generate new bundle, Verify new bundle matches existing, etc. etc.) to fail with `exit 1` when necessary so that steps fail when they need to and there is some problem?  That's what I was generally asking in this issue.

As far as branch protection, I'm only a collaborator here, not a repo owner (i.e. I do not see a SETTINGS tab above the repo)  So I am limited in what I can do.  I would like to enable main branch protection, as well as setup the checks that must past before allowing merges to happen.  I asked the repo owner in one of the issues on his other repos if I could be given co-owner access... we shall see.

**Comment by wardellbagby** [comment]
Ah, I understand you. Yes, I'm somewhat confident in the bundle check logic. I tested it extensively (both purposefully and accidentally a few times 😅). I'm fully confident that the check will correctly fail if the bundle isn't updated. It's much more likely that the check will incorrectly fail when the bundle doesn't actually need to be updated. Which could be annoying for PRs but still solves the problem of enforcing that the bundle always matches the branch.

Also, shame about the branch protection.

**Comment by thadguidry** [comment]
Closing as non-issue as per @wardellbagby comments above.
